version: "2"
services:
  redis:
    image: redislabs/redisearch:2.2.1
    ports:
      - "6379"

  backend:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    links:
      - redis:redis
    volumes:
      - /var/lib/flatpak
